### ISSUE TITLE
migrations are throwing errors

### ISSUE THREAD

**Issue by PLAZMAMA** [PLAZMAMA/IdeaCollector#5]
migrations work fine when running in a docker container using docker-compose. However, when running locally with the same pipenv it does not work.

**Comment by attiasr** [comment]
accessing the DB from docker and from the local terminal cannot be the same.
- when you access the DB from docker you usually use the name of the service to connect to it
- when accessing it from your terminal, you should use localhost BUT you need to make sure to exposes the DB port

**Comment by PLAZMAMA** [comment]
works fine just needs to run the migrations in the docker of the django while running the postgres server as well
