### ISSUE TITLE
docker-compose is not needed to build the image

### ISSUE THREAD

**Issue by attiasr** [PLAZMAMA/IdeaCollector#9]
https://github.com/PLAZMAMA/IdeaCollector/blob/d6f28c408e0e91f91a0eb793b7546950a13aad68/.gitlab-ci.yml#L15

**Comment by PLAZMAMA** [comment]
I'm using docker-compose for the testing. Is that not how it should be?

**Comment by attiasr** [comment]
ideally no, docker-compose is complex and needs installation.

**Comment by PLAZMAMA** [comment]
I switched to run the tests on one container with sqlite instead of two containers one running postgres and one running the django app.
